### PR TITLE
append changelog to fulfill the license obligation

### PR DESCRIPTION
**Pull request by xiayingfeng**
### Missing notice for modifications on original work (violation of [APACHE-2.0](https://opensource.org/licenses/Apache-2.0))

[**Modification terms and conditions in license**] The original work should be honored while the modifications on it should be attached with prominent notices as the license [APACHE-2.0](https://opensource.org/licenses/Apache-2.0) dictates. Your project is a forking project from [AndreyAsadchy/Xtra](https://github.com/AndreyAsadchy/Xtra) which adopts [APACHE-2.0](https://opensource.org/licenses/Apache-2.0) as its project license. The modification terms and conditions of [APACHE-2.0](https://opensource.org/licenses/Apache-2.0) dictate that:

>[APACHE-2.0](https://opensource.org/licenses/Apache-2.0):
>
>*... You must cause any modified files to carry prominent notices stating that You changed the files ...*

Therefore, I think the project is obligated to abide by the modification terms and conditions in [APACHE-2.0](https://opensource.org/licenses/Apache-2.0).

[**Violation of modification terms and conditions**] I run through your history, and it turns out that you have conducted modifications to the *source files* of original work while didn't provide prominent notices. You have **10** commits which conduct modifications to the original work, all of which are not declared in [README.md](https://github.com/crackededed/Xtra/blob/master/README.md). Specifically, of the **10** commits, **10** commits are not announced in the file. According to the license terms and conditions above, it is regarded as license violation. Thus, to avoid potential legal risks, I would suggest you carry out prominent notices for the **10** commits. 

[**Fix**] For your convenience, I created a PR with by picking up modification-related commit messages. It adds a few lines in [changelog](https://github.com/xiayingfeng/Xtra/blob/fulfill-license-obligation/changelog) without touching the codebase. Please be comfortable to check it out. 

Full details of the report you could refer to the [html](https://htmlpreview.github.io/?https://github.com/xiayingfeng/Xtra/blob/master/page.html) file attached. Hope it helps!

Cheers!

### CODE REVIEW

**Comment by crackededed** [comment]
isn't the git log enough?

**Comment by xiayingfeng** [comment]
Hello, the Apache-2.0 requires the contributors to *cause any modified files to carry prominent notices stating that You changed the files*. In fact, the information in git mechanism is enough, however, to avoid unnecessary legal risks and make open source community more standardized, we would suggest you to put a note in the top directory, something like MODIFICATION.md or README.md, and write "In compliance with the Apache 2.0 license: I declare that this version of the program contains my modifications, which can be seen through the usual "git" mechanism."

**Comment by AndreyAsadchy** [comment]
It's not even Apache.

**Comment by xiayingfeng** [comment]
hah, sorry then, I made something wrong about it, but [AGPL](https://opensource.org/license/agpl-v3-html/) also has similar provisions.

>You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:
>a) The work must carry prominent notices stating that you modified it, and giving a relevant date.

Thanks for your review.

**Pull request closed without merging**
