### PR TITLE
Added Audio Compressor

### PR DESCRIPTION
**Pull request by devalexx**
Really missing FrankerFaceZ Audio Compressor feature in this app. I'm not a professional Android developer, so I hope you might help me with this PR to merge it into master.

### CODE REVIEW

**Comment by crackededed** [comment]
this doesn't work after switching to audio only quality since a different player is created in the audio service. i'm working on switching to using only one player so wait until this is done: https://github.com/crackededed/Xtra/tree/media3

**Comment by crackededed** [comment]
can you try adding this to the latest version now?

**Comment by devalexx** [comment]
rebased on the latest master branch

**Comment by crackededed** [comment]
thanks

**Pull request merged**
