### PR TITLE
Add support for adaptive and themed icons

### LINKED ISSUE #151: Add Material You icon
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

Since android 13 icons should follow Material You. This is very simple to do

### PR DESCRIPTION
**Pull request by Aritzherrero4**
This change adds support for Android's adaptive icons and themed icons (A13+).

This PR fixes #151 

image

Tested with the emulator on android 5.1 and 13 and with a Pixel 7Pro and running android 13.

### CODE REVIEW

**Comment by xPaw** [comment]
Icon looks kinda low quality compared to other apps. Was it scaled incorrectly?

**Comment by Aritzherrero4** [comment]
I know that some apps use vectorized icons, so the quality is way better. But I don't really know how they work.
Since I don't have the original icon, used the highest quality one available in the source code and adapted it and used the tool available on android studio to scale it.

If someone knows how to create a better icon, create a PR replacing the ic_launcher_monochrome or send it to me and I'll do it.

**Comment by xPaw** [comment]
Unless the original author happens to have the sources for the icon, I don't think there's much to be found.

There's a 512px icon here though: https://raw.githubusercontent.com/AndreyAsadchy/Xtra/b2fce3f329bac290b98fe8e6fcfbcdd44dae9769/app/src/main/ic_launcher-web.png

I tried converting it to svg, but ended up just recreating the two lines as vector (i'm not a designer), should be good enough for the monochrome version?

**Comment by Aritzherrero4** [comment]
I think I can easily convert that to a vectorDrawable and add it as the monochrome icon. I'll check and if it works, I'll send a new PR with the new icon this weekend. 

Thanks for the svg.

**Pull request merged**
