### PR TITLE
Fix downloads from the video player

### LINKED ISSUE #208: Missing files access permission to download
There is an issue when I want to download a video clip, it says "Required permissions have been denied", but it doesn't ask for the permission to access files. And I can't set it manually in the settings as the app doesn't ask for it.
My phone is on Android 13.

### PR DESCRIPTION
**Pull request by Aritzherrero4**
Trying to download a VoD or a clip from the video player causes the app to throw an error of missing permissions.

The app no longer uses nor asks for that permission since, the download location is inside the storage of the app (android/data/...). But on those two cases, the app checks the old permissions. Moreover, the old permissions are no longer accessible on Android 13 (Scoped storage).

This change fixes the issue by removing the unnecessary checks and fixes a crash causes by an unhandled result of the process to calculate the start time (index) for the download. (Documented on the code.)

This PR fixes #208

### CODE REVIEW

**Comment by AndreyAsadchy** [comment]
@Aritzherrero4 @crackededed Have you guys tried this on Android 4? IIRC the permissions are needed for it, even if it's in the private app folder. 

Anyway that's if we still support Android 4, there is a separate release for it, from what I see.

**Comment by Aritzherrero4** [comment]
Hi @AndreyAsadchy,
This change just follows the behavior of the other download buttons of the app. That hasStoragePermission function wasn't used anywhere else, so on Android 4.1(API 16) should be the same as it was for the other buttons. I don't even know if they were permission request dialogs back then.

You are correct on that, apps needed that before [API 19](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE)  to write to their own storage. But, the app still declares the write/read storage permissions [on the manifest](https://github.com/crackededed/Xtra/blob/e89533cffb87e0f722c226dbd4c3605c05867d6b/app/src/main/AndroidManifest.xml#L8).

Since I don't have any devices running android 4.1, I have just tested the api_16 branch on the emulator and the app is not able to play anything, but it can download clips or videos and the permission appears to be granted:
image

But I cannot guarantee that it works on real devices.

**Comment by crackededed** [comment]
on android 4 all permissions are granted when installing the app so it should be fine for now

**Comment by AndreyAsadchy** [comment]
Thanks for looking into it! Still be cautious with such changes. Sometimes things work on an emulator or your phone, but some custom roms like Xiaomi might have a different behaviour. 

Idk some old code might be there for a reason 🤷‍♂️

**Pull request merged**
